<?php

/**
 * @file
 * Module provides ShortCodes filter framework and API (like WP ShortCodes)
 */

/**
 * Implements hook_migration_plugins_alter().
 */
function shortcode_migration_plugins_alter(array &$migrations) {
  if (isset($migrations['d7_filter_format'])) {
    $migration = &$migrations['d7_filter_format'];

    // Add 7.x-2.x to 2.0.x filter ID mapping.
    $migration['process']['filters']['process']['id']['map']['shortcode_text_corrector'] = 'shortcode_corrector';
  }
}
