commerce_payment.commerce_payment_gateway.plugin.commerce_stripe_checkout_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    live_secret_key:
      type: string
      label: 'Live Test Secret key'
    secret_key:
      type: string
      label: 'Test Secret key'
